### ISSUE TITLE
Could not find module `ember-cli-spinjs/acceptance-tests/index`

### ISSUE THREAD

**Issue by hoboman313** [kiwiupover/ember-cli-spinjs#129]
I'm getting a error(doesn't break tests though) when running my test suite stating that the ember-cli-spinks/acceptance-tests/index cannot be found. 
As I look at my node modules directories, I see that ember-cli-spinjs/tests directory doesn't exist for me locally, but the app/acceptance-tests/index.js files still makes a reference to it.

**Comment by kiwiupover** [comment]
Thanks @hoboman313 

I have a fix in https://github.com/kiwiupover/ember-cli-spinjs/pull/130

Cheers 
Dave
