### ISSUE TITLE
Cannot set zIndex

### ISSUE THREAD

**Issue by 0x0badc0de** [kiwiupover/ember-cli-spinjs#134]
Hi guys,
There is a PR #12 which allows to pass in `zIndex` but this was removed in #13 most likely by mistake. If so - can it be added back?

**Comment by kiwiupover** [comment]
Sounds like a good plan.

**Comment by kiwiupover** [comment]
@0x0badc0de thanks for the heads up fixed by #136

**Comment by 0x0badc0de** [comment]
Awesome, thanks @kiwiupover !
