### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by Dainii** [kiwiupover/ember-cli-spinjs#144]
Hi, thanks a lot for this plugin ;)

The one line configuration works well but not with the 'config file' version. I create the ember-cli app with the name 'webapp' but the root directory's name is different. When I call a template with `{{ember-spinner config='standard'}}` it results this error `Uncaught Error: Could not find module webapp/config/ember-spinner/standard imported from (require)` and this is right because "webapp" is not the name of the root directory. 

Is there a way to set the correct name somewhere ?

Thx

**Comment by mtangoo** [comment]
Found same error. I hope you fix this one (or at least explain it)

**Comment by kiwiupover** [comment]
@Dainii and @mtangoo thanks for bringing this up again.

**Comment by mtangoo** [comment]
Checking other issues, it seems the explanation is vague. The explanation should explicitily point to `/app-root-folder/app/config/ember-spinner/standard.js` instead of what is current there

**Comment by kiwiupover** [comment]
@Dainii would you like to update the README to explain the config setup and create a PR.
