### ISSUE TITLE
Request: Release new version

### ISSUE THREAD

**Issue by oliverwilkie** [kiwiupover/ember-cli-spinjs#25]
Was curious when you are planning your next release?

Would be nice for those Ember 2 depreciation warnings to go away!

Thanks for maintaining this addon!

**Comment by oliverwilkie** [comment]
![screen shot 2016-01-07 at 4 49 23 pm](https://cloud.githubusercontent.com/assets/10522493/12187202/b2781600-b55e-11e5-8a0d-e406c157218c.png)

**Comment by kiwiupover** [comment]
I just release version 1.3 a few days ago that should remover the warnings.
Let me know if there is still an issue.

Cheers
Dave.

**Comment by oliverwilkie** [comment]
Great thanks!
