### ISSUE TITLE
Unable to stop/ start at desired place

### ISSUE THREAD

**Issue by ramagirinagarjuna** [kiwiupover/ember-cli-spinjs#28]
Hi,

I'm successfully installed the add on but I could not start the spinner on click of a button and stop at the end of processing an event. Could you please let me know how to do that.

Thanks,
Nagarjuna

**Comment by kiwiupover** [comment]
G'day @ramagirinagarjuna 

You can show and hide the spinner inside a boolean. 

```hbs
{{#if showSpinner}}
    {{ember-spinner}}
{{else}}
    {{my-component name=' Nagarjuna'}}
{{/if}}
```

There is a loading template for each of your routes in your ember app. Ember will show that template when your route is loading. So you can create a file `app/template/loading.hbs` and the below code.

```hbs
{{ember-spinner}}
```

**Comment by ramagirinagarjuna** [comment]
Thanks david. You saved my day. works like a charm.

**Comment by kiwiupover** [comment]
Perfect!  🎉
