### ISSUE TITLE
Proposal: Different config directory

### ISSUE THREAD

**Issue by hoboman313** [kiwiupover/ember-cli-spinjs#69]
It feels weird to me to have to create a config folder under app/. Personally I'd prefer to keep configs in one place: the top most config folder. Is it possible to do that?

**Comment by kiwiupover** [comment]
Hi @hoboman313 I understand what you are saying here. I while ago only the app folder was watched to file changes which is the reason to add a config folder to the app folder. 

If you would like to submit a PR that would support both locations I would total welcome that.

**Comment by kiwiupover** [comment]
@hoboman313 I'm going to close this issue. If you really think this is an issue let me know. Cheers
