### ISSUE TITLE
Remove spin.js from bower dependencies

### ISSUE THREAD

**Issue by hoboman313** [kiwiupover/ember-cli-spinjs#73]
Bower is basically an obsolete package manager as the JS world transitions to npm/yarn. Please consider removing spin.js as a bower dependencies and grabbing it with npm instead.

**Comment by kiwiupover** [comment]
I did that a little while ago in this PR https://github.com/kiwiupover/ember-cli-spinjs/pull/61

Is this what you were talking about?

**Comment by hoboman313** [comment]
Yes, that is what I meant. Note that it's in the blueprints to install it via bower.
ember-cli-spinjs/blueprints/ember-cli-spinjs/index.js

**Comment by kiwiupover** [comment]
You are right I will update `addBowerPackageToProject` to `addPackageToProject` this evening unless you would like to open a PR @hoboman313.

Cheers for pointing out the issue.

**Comment by hoboman313** [comment]
I'm not familiar with writing ember adons so I would prefer if you did it. 
It feels like addPackageToProject isn't needed here since spin.js is already pulled in through package.json

**Comment by kiwiupover** [comment]
Sure I get that. Cheers.

**Comment by kiwiupover** [comment]
Thanks again for pointing out the extra code @hoboman313. It has been fixed by #74
